name: route_observer_mixin
description: RouteObserveMixin provides easy access to didPush/didPop/didPushNext/didPopNext.
version: 1.5.0+1
homepage: https://github.com/mono0926/route_observer_mixin
environment:
  sdk: ">=2.12.0-0 <3.0.0"
dependencies:
  disposable_provider: ">=2.3.0 <3.0.0"
  flutter:
    sdk: flutter
  provider: ">=5.0.0-0 <6.0.0"
  riverpod: ">=0.13.0-0 <1.0.0"
  rxdart: ">=0.26.0-0 <1.0.0"
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: